### ISSUE TITLE
cannot cache function 'log_beta'

### ISSUE THREAD

**Issue by av-jt** [Roth-Lab/pyclone#5]
Hello, 

I am getting this error when i try to run PyClone (0.13.1) on centos7
i have installed all the required packages form python (including numba, 0.41.0).

Do you know why is this error being given? I am not so familiar with numba and the jit function that is used here. 

PyClone -h

Traceback (most recent call last):
  File "/usr/bin/PyClone", line 9, in <module>
    load_entry_point('PyClone==0.13.1', 'console_scripts', 'PyClone')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/pyclone/cli.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/pyclone/run.py", line 21, in <module>
  File "build/bdist.linux-x86_64/egg/pyclone/pyclone_beta_binomial.py", line 21, in <module>
  File "build/bdist.linux-x86_64/egg/pyclone/math_utils.py", line 26, in <module>
  File "/usr/lib64/python2.7/site-packages/numba/decorators.py", line 191, in wrapper
    disp.enable_caching()
  File "/usr/lib64/python2.7/site-packages/numba/dispatcher.py", line 566, in enable_caching
    self._cache = FunctionCache(self.py_func)
  File "/usr/lib64/python2.7/site-packages/numba/caching.py", line 614, in __init__
    self._impl = self._impl_class(py_func)
  File "/usr/lib64/python2.7/site-packages/numba/caching.py", line 349, in __init__
    "for file %r" % (qualname, source_path))
RuntimeError: cannot cache function 'log_beta': no locator available for file 'build/bdist.linux-x86_64/egg/pyclone/math_utils.py'

**Comment by omula** [comment]
You have to install it using pip and not python. In case you end up with an egg file (zipped) it won't work due to numba caching.

**Comment by renyongzhe** [comment]
> You have to install it using pip and not python. In case you end up with an egg file (zipped) it won't work due to numba caching.

how to install pyclone using pip?

**Comment by omula** [comment]
IIRC:

1. Clone the repo.
2. Enter to the folder.
3. pip install .

**Comment by mark-welsh** [comment]
^^^ this worked for me. I installed manually using pyenv/pip and received the same error after running `python setup.py install`

running `pip install .` worked just fine instead
